#!/bin/sh

CONFIG_FS=/sys/kernel/config
CONFIG_DIR=$CONFIG_FS/usb_gadget
GADGET_DIR=$CONFIG_DIR/g1
CONFIG_NAME="c.1"

SERIALNUMBER=$(getprop ro.serialno)
MANUFACTURER=$(getprop ro.product.vendor.manufacturer)
PRODUCT=$(getprop ro.product.vendor.model)

CONTROLLER=$(ls /sys/class/udc 2>/dev/null | head -n1)
setprop sys.usb.controller "$CONTROLLER"

write() {
test -e "$1" || return
printf "%s" "$2" > "$1"
}

symlink() {
rm -f "$2"
ln -s "$1" "$2"
}

unbind_udc() {
if [ -e "$GADGET_DIR/UDC" ]; then
echo "" > "$GADGET_DIR/UDC" 2>/dev/null
fi
}

bind_udc() {
sleep 1
unbind_udc
sleep 1
write "$GADGET_DIR/UDC" "$CONTROLLER"
}

reset_usb() {
rm -f $GADGET_DIR/configs/$CONFIG_NAME/mtp.mtp
rm -f $GADGET_DIR/configs/$CONFIG_NAME/f1
rm -f $GADGET_DIR/configs/$CONFIG_NAME/rndis.usb0
}

setup_mtp() {
reset_usb
write $GADGET_DIR/functions/mtp.mtp/os_desc/interface.MTP/compatible_id "mtp"
write $GADGET_DIR/configs/$CONFIG_NAME/strings/0x409/configuration "mtp"
symlink $GADGET_DIR/functions/mtp.mtp
$GADGET_DIR/configs/$CONFIG_NAME/mtp.mtp

```
bind_udc
setprop sys.usb.state mtp
```

}

setup_mtp_adb() {
reset_usb
write $GADGET_DIR/functions/mtp.mtp/os_desc/interface.MTP/compatible_id "mtp_adb"
write $GADGET_DIR/configs/$CONFIG_NAME/strings/0x409/configuration "mtp_adb"

```
symlink $GADGET_DIR/functions/mtp.mtp \
        $GADGET_DIR/configs/$CONFIG_NAME/mtp.mtp

symlink $GADGET_DIR/functions/ffs.adb \
        $GADGET_DIR/configs/$CONFIG_NAME/f1

start android-tools-adbd
sleep 2

bind_udc
setprop sys.usb.state mtp,adb
```

}

setup_boot() {

```
if ! mount | grep -q "$CONFIG_FS"; then
    mount -t configfs none $CONFIG_FS
fi

mkdir -p $GADGET_DIR
mkdir -p $GADGET_DIR/strings/0x409
mkdir -p $GADGET_DIR/functions
mkdir -p $GADGET_DIR/configs/$CONFIG_NAME/strings/0x409

write $GADGET_DIR/idVendor 0x04E8
write $GADGET_DIR/bcdDevice 0x0223
write $GADGET_DIR/bcdUSB 0x0200

write $GADGET_DIR/os_desc/use 1
write $GADGET_DIR/os_desc/b_vendor_code 0x1
write $GADGET_DIR/os_desc/qw_sign "MSFT100"

write $GADGET_DIR/strings/0x409/serialnumber "$SERIALNUMBER"
write $GADGET_DIR/strings/0x409/manufacturer "$MANUFACTURER"
write $GADGET_DIR/strings/0x409/product "$PRODUCT"

mkdir -p $GADGET_DIR/functions/mtp.mtp
mkdir -p $GADGET_DIR/functions/ffs.adb

symlink $GADGET_DIR/configs/$CONFIG_NAME \
        $GADGET_DIR/os_desc/$CONFIG_NAME

mkdir -p /dev/usb-ffs/adb
mount -t functionfs -o uid=32011,gid=32011 adb /dev/usb-ffs/adb 2>/dev/null
chmod 775 /dev/usb-ffs /dev/usb-ffs/adb
```

}

setup_boot

case "$1" in
mtp)
setup_mtp
;;
mtp_adb)
setup_mtp_adb
;;
*)
echo "No configuration selected."
;;
esac

exit 0
