[Service]
ExecStartPre=-/bin/mount -o remount,rw /
ExecStartPre=-/bin/mkdir -p /android/mnt/vendor /android/prism /android/optics
ExecStartPre=-/bin/chmod 755 /android/mnt/vendor /android/prism /android/optics
# Set short firmware loading timeout so container startup doesn't block itself
ExecStartPre=-/bin/bash -c "echo 2 > /sys/class/firmware/timeout"
